[package]
name = "mqtt-webhook"
version = "0.1.0"
authors = ["Alexandre Peyroux <alex@px.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
redis = "0.12.0"
