[package]
name = "mqtt-webhook"
rversion = "0.1.0"
authors = ["Alexandre Peyroux <alex@px.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
