#!/bin/env python

from flask import (Flask,
                   request,
                   jsonify)
import click
from pampy import match, _

NEOPARC = "NEOPARC"
IDENT = "IDENT"
AUTH = "AUTH"
UNAUTH = "401"

app = Flask(__name__)


@app.route('/auth', methods=['POST'])
def index():
    body = request.json
    x = match(body['username'].split(':'),
              ["neoparc", _, _], NEOPARC,
              ["ident", _, _], IDENT,
              ["auth", _, _], AUTH,
              _, UNAUTH)
    return jsonify({'result': 'ok', 'message': x})


@click.command()
@click.option('--port', default="5000", help='listen port')
@click.option('--host', default="0.0.0.0", help='listen host')
def runApp(port, host):
    click.echo("start mqtt-webhook ws ...")
    app.run(host=host, port=port)


if __name__ == "__main__":
    runApp()
