#!/bin/env python

from flask import (Flask,
                   request,
                   jsonify,
                   abort)
import click
from pampy import match, _

NEOPARC = "NEOPARC"
IDENT = "IDENT"
AUTH = "AUTH"
UNAUTH = "401"

app = Flask(__name__)


@app.route('/auth', methods=['POST'])
def index():
    body = request.json
    headers = request.headers

    if body is None:
        abort(400)

    '''
    Si le header vernemq-hook est un auth_on_register
    '''
    if "auth_on_register" == (headers['vernemq-hook']
                              if 'vernemq-hook' in headers else None):

        auth = match(
            body['username'].split(':') if 'username' in body else "nothing",
            ["neoparc", _, _], NEOPARC,
            ["ident", _, _], IDENT,
            ["auth", _, _], AUTH,
            _, UNAUTH
        )

        if auth == NEOPARC:
            app.logger.info("Auth {}".format(body))
            return jsonify({'result': 'ok'})
        elif auth == IDENT:
            app.logger.info("Auth {}".format(body))
            return jsonify({'result': 'ok'})
        elif auth == AUTH:
            app.logger.info("Auth {}".format(body))
            return jsonify({'result': 'ok'})
        else:
            app.logger.info("Unauthorized")
            return jsonify({'result': 'next'})
            # abort(401)

    # Autres cas (header not match)
    else:
        abort(400)


@click.command()
@click.option('--port', default="5000", help='listen port')
@click.option('--host', default="0.0.0.0", help='listen host')
@click.option('--debug', default=False, help='debug flask')
def runApp(port=5000, host="0.0.0.0", debug=False):
    click.echo("start mqtt-webhook ws ...")
    app.run(host=host, port=port, debug=debug)


if __name__ == "__main__":
    runApp()
